version: "3"
services: 
  # 服务名称
  php:
    # 镜像名字
    image: dnmp-php:${PHP_VERSION}
    # 容器名称
    container_name: dnmp-php
    # 指定构建的 Dockerfile 文件
    build:
      context: ./services/php74
      # 设置构建参数
      args:
        TZ: ${TZ}
        CONTAINER_PHP_PACKAGE_URL: ${CONTAINER_PHP_PACKAGE_URL}
        PHP_VERSION: ${PHP_VERSION}
        PHP_WORK_DIR: ${PHP_WORK_DIR}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
    # 设置环境变量
    environment:                        
      - TZ=${TZ}
    # 对外暴露端口
    expose:
      - 9501
    extra_hosts:
      - "www.site.com:127.0.0.1"
    # 端口映射
    ports:
      - "9501:9501"
      - "9502:9502"
    # 将宿主机的目录挂载到容器中
    volumes:
      - ${PHP_CONF_INI_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_CONF_FPM_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_SOURCE_DIR}:${PHP_WORK_DIR}:rw
      - ${PHP_LOG_DIR}:/var/log/php
    # 指定容器退出后的重启策略为始终重启
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - docker-dnmp-default

  # 服务名称
  nginx:
    # 镜像名称
    image: dnmp-nginx:${NGINX_VERSION}
    # 容器名称
    container_name: dnmp-nginx
    # 指定 Dockerfile
    build:
      context: ./services/nginx
      args:
        TZ: ${TZ}
        CONTAINER_NGINX_PACKAGE_URL: ${CONTAINER_NGINX_PACKAGE_URL}
        NGINX_VERSION: ${NGINX_VERSION}
    # 设置环境变量
    environment:                        
      - TZ=${TZ}
    # 端口映射
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    links:
      - php
    # 磁盘挂载
    volumes:
      - ${NGINX_SOURCE_DIR}:${NGINX_WORK_DIR}:rw
      - ${NGINX_CONF_NGINX_CONF}:/etc/nginx/nginx.conf:rw
      - ${NGINX_CONF_DIR_SSL}:/etc/nginx/ssl/:rw
      - ${NGINX_CONF_DIR_CONFD}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_DIR_FASTCGI}:/etc/nginx/fastcgi/:rw
      - ${NGINX_CONF_DIR_ERROR}:/etc/nginx/error/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - docker-dnmp-default

     
  # 服务名称
  mysql:
    # 镜像名称
    image: dnmp-mysql:${MYSQL_VERSION}
    # 容器名称
    container_name: dnmp-mysql
    build:
      context: ./services/mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    # 环境变量
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST}"
      TZ: "$TZ"
    # 端口映射
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    # 磁盘挂载
    volumes:
      - ${MYSQL_CONF_MYSQL_CNF}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_CONF_DIR_DATA}:/var/lib/mysql/:rw
      - ${MYSQL_LOG_DIR}:/var/log/mysql/:rw
    restart: always
    networks:
      - docker-dnmp-default
    

  # 服务名称
  redis:
    # 镜像名称
    image: dnmp-redis:${REDIS_VERSION}
    # 容器名称
    container_name: dnmp-redis
    # 编译文件
    build:
      context: ./services/redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    # 环境变量
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      TZ: "$TZ"
    # 端口映射
    ports:
      - "${REDIS_HOST_PORT}:6379"
    # 磁盘挂载
    volumes:
      - ${REDIS_CONF_REDIS_CONF}:/etc/redis.conf:ro
      - ${REDIS_CONF_DIR_DATA}:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf" , "--requirepass" , "${REDIS_PASSWORD}"]
    restart: always
    networks:
      - docker-dnmp-default


#======================================================================================> [kafka]

  kafka-node1:
    # 容器名称
    container_name: dnmp-kafka-node1
    # 镜像名称
    image: bitnami/kafka:${KAFKA_VERSION}
    user: root
    # 端口映射
    ports:
      - ${KAFKA_PORT_CLIENT_NODE1}:9092
      - ${KAFKA_PORT_CONTROLLER_NODE1}:9093
    # 磁盘挂载
    volumes:
      # 数据目录
      - ${KAFKA_DIR_DATA_NODE1}:/bitnami/kafka:rw
    environment:
      - TZ="$TZ"
      # 指定Kafka节点的ID为1，唯一
      - KAFKA_CFG_NODE_ID=1
      # 启用KRaft模式 , 即Kafka替代Zookeeper
      - KAFKA_ENABLE_KRAFT=yes
      # 设置Kafka节点的角色 既要做 broker 又要做 controller
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # KRaft集群的ID ， 构造一个 UUID 
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      # 指定供外部使用的控制类请求信息
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  
      # 定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      # 监听器的地址为当前节点的IP和相应的端口
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 
      # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # 设置控制器的选举集群成员
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-node1:9093,2@kafka-node2:9093,3@kafka-node3:9093
      # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 禁止自动创建主题
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false 
      # 设置broker最大内存，和初始内存
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
    restart: always
    networks:
      - docker-dnmp-default

  kafka-node2:
    # 容器名称
    container_name: dnmp-kafka-node2
    # 镜像名称
    image: bitnami/kafka:${KAFKA_VERSION}
    user: root
    # 端口映射
    ports:
      - ${KAFKA_PORT_CLIENT_NODE2}:9092
      - ${KAFKA_PORT_CONTROLLER_NODE2}:9093
    # 磁盘挂载
    volumes:
      # 数据目录
      - ${KAFKA_DIR_DATA_NODE2}:/bitnami/kafka:rw
    environment:
      - TZ="$TZ"
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-node1:9093,2@kafka-node2:9093,3@kafka-node3:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false 
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
    restart: always
    networks:
      - docker-dnmp-default

  kafka-node3:
    # 容器名称
    container_name: dnmp-kafka-node3
    # 镜像名称
    image: bitnami/kafka:${KAFKA_VERSION}
    user: root
    # 端口映射
    ports:
      - ${KAFKA_PORT_CLIENT_NODE3}:9092
      - ${KAFKA_PORT_CONTROLLER_NODE3}:9093
    # 磁盘挂载
    volumes:
      # 数据目录
      - ${KAFKA_DIR_DATA_NODE3}:/bitnami/kafka:rw
    environment:
      - TZ="$TZ"
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-node1:9093,2@kafka-node2:9093,3@kafka-node3:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false 
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
    restart: always
    networks:
      - docker-dnmp-default


#======================================================================================> [kafka]






#======================================================================================> [etcd] START

  etcd-node1:
    # 容器名称
    container_name: dnmp-etcd-node1
    # 镜像名称
    image: bitnami/etcd:${ETCD_VERSION}
    # 端口映射
    ports:
      - ${ETCD_PORT_CLIENT_NODE1}:2379
      - ${ETCD_PORT_PEER_NODE1}:2380
    # 磁盘挂载
    volumes:
      # 数据目录
      - ${ETCD_DIR_DATA_NODE1}:/bitnami/etcd:rw
    environment:  
      - TZ="$TZ"
      # etcd 的名字
      - ETCD_NAME=etcd1    
      # 版本 API (2 or 3)
      - ETCDCTL_API=3
      # ETCD集 群的成员之间使用 token
      - ETCD_TOKE=ETCD-GROUP-TOKEN         
      # 日志级别                    
      - ETCD_LOG_LEVEL=debug
      # 允许不用密码登录
      - ALLOW_NONE_AUTHENTICATION=yes      
      #  监听在本地所有网络接口 - 于监听客户端通信的 URL 列表                 
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379          
      # 监听在本地所有网络接口 - 用于监听伙伴通信的 URL 列表
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380      
      # 列出这个成员的客户端URL，通告给集群中的其他成员     
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node1:2379
      # 列出这个成员的伙伴 URL 以便通告给集群的其他成员        
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node1:2380  
      # 集群配置-初始化一个集群记号
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster             
      # 集群配置-集群节点配置
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd-node1:2380,etcd2=http://etcd-node2:2380,etcd3=http://etcd-node3:2380 
      # 初始化集群状态
      - ETCD_INITIAL_CLUSTER_STATE=new                      
    restart: always
    networks:
      - docker-dnmp-default

  etcd-node2:
    # 容器名称
    container_name: dnmp-etcd-node2
    # 镜像名称
    image: bitnami/etcd:${ETCD_VERSION}
    # 端口映射
    ports:
      - ${ETCD_PORT_CLIENT_NODE2}:2379
      - ${ETCD_PORT_PEER_NODE2}:2380
    # 磁盘挂载
    volumes:
      # 数据目录
      - ${ETCD_DIR_DATA_NODE2}:/bitnami/etcd:rw
    environment:  
      - TZ="$TZ"
      - ETCD_NAME=etcd2
      - ETCDCTL_API=3
      - ETCD_TOKE=ETCD-GROUP-TOKEN         
      - ETCD_LOG_LEVEL=debug
      - ALLOW_NONE_AUTHENTICATION=yes      
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379          
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380      
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node2:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node2:2380  
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster             
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd-node1:2380,etcd2=http://etcd-node2:2380,etcd3=http://etcd-node3:2380 
      - ETCD_INITIAL_CLUSTER_STATE=new                      
    restart: always
    networks:
      - docker-dnmp-default

  etcd-node3:
    # 容器名称
    container_name: dnmp-etcd-node3
    # 镜像名称
    image: bitnami/etcd:${ETCD_VERSION}
    # 端口映射
    ports:
      - ${ETCD_PORT_CLIENT_NODE3}:2379
      - ${ETCD_PORT_PEER_NODE3}:2380
    # 磁盘挂载
    volumes:
      # 数据目录
      - ${ETCD_DIR_DATA_NODE3}:/bitnami/etcd:rw
    environment:  
      - TZ="$TZ"
      - ETCD_NAME=etcd3
      - ETCDCTL_API=3
      - ETCD_TOKE=ETCD-GROUP-TOKEN         
      - ETCD_LOG_LEVEL=debug
      - ALLOW_NONE_AUTHENTICATION=yes      
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379          
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380      
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node3:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node3:2380  
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster             
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd-node1:2380,etcd2=http://etcd-node2:2380,etcd3=http://etcd-node3:2380 
      - ETCD_INITIAL_CLUSTER_STATE=new                      
    restart: always
    networks:
      - docker-dnmp-default

#======================================================================================> [etcd] END



#======================================================================================> [influxdb] START

  influxdb:
    container_name: dnmp-influxdb
    image: influxdb:${INFLUXDB_VERSION}
    ports:
      - "${INFLUXDB_PORT}:8086"
    volumes:
      - ${INFLUXDB_DIR_DATA}:/var/lib/influxdb:rw
    environment:
      - TZ="$TZ"
      # InfluxDB初始化的模式为“setup”
      - DOCKER_INFLUXDB_INIT_MODE=setup
      # InfluxDB初始化时的管理员用户名密码
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_CONF_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_CONF_PWD}
      # InfluxDB初始化时创建的组织（Organization）
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_CONF_ORG}
      # InfluxDB初始化时创建的数据存储桶（Bucket）
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_CONF_BUCKET}
      # InfluxDB配置文件的路径
      - INFLUX_CONFIGS_PATH=/etc/influxdb2/influx-configs
      # InfluxDB数据存储的 BoltDB 文件的路径
      - INFLUXD_BOLT_PATH=/var/lib/influxdb2/influxd.bolt
      # InfluxDB数据引擎的路径，用于存储实际的时间序列数据
      - INFLUXD_ENGINE_PATH=/var/lib/influxdb2/engine
    restart: always
    networks:
      - docker-dnmp-default
      
#======================================================================================> [influxdb] END
    


#======================================================================================> [grafana] START

  grafana:
    # 容器名称
    container_name: dnmp-grafana
    # 镜像名称
    image: grafana/grafana:${GRAFANA_VERSION}
    # 端口映射
    ports:
      - ${GRAFANA_PORT}:3000
    # 磁盘挂载
    volumes:
      - ${GRAFANA_DIR_DATA}:/var/lib/grafana
      - ${GRAFANA_CONF_INI}:/etc/grafana/grafana.ini:rw
    environment:
      - TZ="$TZ"
      - GF_SECURITY_ADMIN_USER=${GRAFANA_CONF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_CONF_PWD}
    restart: always
    networks:
      - docker-dnmp-default
      
      
#======================================================================================> [grafana] END
    



#======================================================================================> [elasticsearch] START
      
  es-node1:
    # 容器名称
    container_name: dnmp-es-node1
    # 镜像名称
    image: elasticsearch:${ES_VERSION}
    # 端口映射
    ports:
      - ${ES_REST_PORT_NODE1}:9200
      - ${ES_TCP_PORT_NODE1}:9300
    # 磁盘挂载
    volumes:
      - ${ES_CONF_YML_NODE1}:/usr/share/elasticsearch/config/elasticsearch.yml:rw
      - ${ES_DIR_DATA_NODE1}:/usr/share/elasticsearch/data
      - ${ES_DIR_PLUGINS_NODE1}:/usr/share/elasticsearch/plugins
      - ${ES_DIR_LOG_NODE1}:/usr/share/elasticsearch/logs
    environment:
      - TZ="$TZ"
      # 设置环境变量LANG
      - LANG="en_US.UTF-8"
      # 设置节点名称
      - node.name=es-node1
      # 设置集群的名称
      - cluster.name=docker-es-cluster
      # 提供集群中其他主机的列表
      - discovery.seed_hosts=es-node2,es-node3
      # 第一次选举中符合主机资格的节点的集合
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      # 将内存锁设置为true，以限制Elasticsearch可以使用的内存量
      - bootstrap.memory_lock=true
      # 禁用X-Pack安全性功能
      - xpack.security.enabled=false
      # 设置Elasticsearch的用户名
      - ELASTIC_USERNAME=elastic
      # 设置Elasticsearch的密码
      - ELASTIC_PASSWORD=test
      # 设置JVM参数，指定最小堆大小和最大堆大小为512MB
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # 设置进程的资源限制
    ulimits:
      # memlock的软限制和硬限制都设置为-1，表示没有限制。
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    networks:
      - docker-dnmp-default

  es-node2:
    # 容器名称
    container_name: dnmp-es-node2
    # 镜像名称
    image: elasticsearch:${ES_VERSION}
    # 端口映射
    ports:
      - ${ES_REST_PORT_NODE2}:9200
      - ${ES_TCP_PORT_NODE2}:9300
    # 磁盘挂载
    volumes:
      - ${ES_CONF_YML_NODE2}:/usr/share/elasticsearch/config/elasticsearch.yml:rw
      - ${ES_DIR_DATA_NODE2}:/usr/share/elasticsearch/data
      - ${ES_DIR_PLUGINS_NODE2}:/usr/share/elasticsearch/plugins
      - ${ES_DIR_LOG_NODE2}:/usr/share/elasticsearch/logs
    environment:
      - TZ="$TZ"
      - LANG="en_US.UTF-8"
      - node.name=es-node2
      - cluster.name=docker-es-cluster
      - discovery.seed_hosts=es-node1,es-node3
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=test
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    networks:
      - docker-dnmp-default
      
  es-node3:
    # 容器名称
    container_name: dnmp-es-node3
    # 镜像名称
    image: elasticsearch:${ES_VERSION}
    # 端口映射
    ports:
      - ${ES_REST_PORT_NODE3}:9200
      - ${ES_TCP_PORT_NODE3}:9300
    # 磁盘挂载
    volumes:
      - ${ES_CONF_YML_NODE3}:/usr/share/elasticsearch/config/elasticsearch.yml:rw
      - ${ES_DIR_DATA_NODE3}:/usr/share/elasticsearch/data
      - ${ES_DIR_PLUGINS_NODE3}:/usr/share/elasticsearch/plugins
      - ${ES_DIR_LOG_NODE3}:/usr/share/elasticsearch/logs
    environment:
      - TZ="$TZ"
      - LANG="en_US.UTF-8"
      - cluster.name=docker-es-cluster
      - node.name=es-node3
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-node1,es-node2,es-node3
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=test
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    networks:
      - docker-dnmp-default

#======================================================================================> [elasticsearch] END
    

#======================================================================================> [kibana] START

  kibana:
    # 容器名称
    container_name: dnmp-kibana
    # 镜像名称
    image: kibana:${KIBANA_VERSION}
    # 端口映射
    ports:
      - ${KIBANA_PORT}:5601
    # 磁盘挂载
    volumes:
      - ${KIBANA_DIR_LOG}:/usr/share/kibana/logs
      - ${KIBANA_DIR_DATA}:/usr/share/kibana/data
      - ${KIBANA_CONF_YML}:/usr/share/kibana/config/kibana.yml
    # 链接其他容器
    links:
      - es-node1:es-node1
      - es-node2:es-node2
      - es-node3:es-node3
    # 设置环境变量
    environment:
      - TZ="$TZ"
      - LANG="en_US.UTF-8"
      # 国际化-中文设置
      - i18n.locale="zh-CN"
      # 系统名称
      - SERVER_NAME=dnmp-kibana
      # 访问用户名
      - ELASTICSEARCH_USERNAME="root"
      # 访问密码
      - ELASTICSEARCH_PASSWORD="123456"
      # 节点 ES
      - ELASTICSEARCH_HOSTS="http://es-node1:9200"
    restart: always
    networks:
      - docker-dnmp-default

#======================================================================================> [kibana] END


# 网络配置
networks:
  # 定义网络名
  docker-dnmp-default:
    # bridge 驱动
    driver: bridge
    # IP 地址管理相关的配置
    ipam:
      driver: default
      config:
       - subnet: 192.168.10.0/24
