version: "3"
services: 
  # 服务名称
  php:
    # 镜像名字
    image: dnmp-php:${PHP_VERSION}
    # 容器名称
    container_name: dnmp-php
    # 指定构建的 Dockerfile 文件
    build:
      context: ./services/php74
      # 设置构建参数
      args:
        TZ: ${TZ}
        CONTAINER_PHP_PACKAGE_URL: ${CONTAINER_PHP_PACKAGE_URL}
        PHP_VERSION: ${PHP_VERSION}
        PHP_WORK_DIR: ${PHP_WORK_DIR}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
    # 设置环境变量
    environment:                        
      - TZ=${TZ}
    # 对外暴露端口
    expose:
      - 9501
    extra_hosts:
      - "www.site.com:127.0.0.1"
    # 端口映射
    ports:
      - "9501:9501"
      - "9502:9502"
    # 将宿主机的目录挂载到容器中
    volumes:
      - ${PHP_CONF_INI_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_CONF_FPM_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_SOURCE_DIR}:${PHP_WORK_DIR}:rw
      - ${PHP_LOG_DIR}:/var/log/php
    # 指定容器退出后的重启策略为始终重启
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - docker-dnmp-default

  # 服务名称
  nginx:
    # 镜像名称
    image: dnmp-nginx:${NGINX_VERSION}
    # 容器名称
    container_name: dnmp-nginx
    # 指定 Dockerfile
    build:
      context: ./services/nginx
      args:
        TZ: ${TZ}
        CONTAINER_NGINX_PACKAGE_URL: ${CONTAINER_NGINX_PACKAGE_URL}
        NGINX_VERSION: ${NGINX_VERSION}
    # 设置环境变量
    environment:                        
      - TZ=${TZ}
    # 端口映射
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    links:
      - php
    # 磁盘挂载
    volumes:
      - ${NGINX_SOURCE_DIR}:${NGINX_WORK_DIR}:rw
      - ${NGINX_CONF_NGINX_CONF}:/etc/nginx/nginx.conf:rw
      - ${NGINX_CONF_DIR_SSL}:/etc/nginx/ssl/:rw
      - ${NGINX_CONF_DIR_CONFD}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_DIR_FASTCGI}:/etc/nginx/fastcgi/:rw
      - ${NGINX_CONF_DIR_ERROR}:/etc/nginx/error/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - docker-dnmp-default

     
  # 服务名称
  mysql:
    # 镜像名称
    image: dnmp-mysql:${MYSQL_VERSION}
    # 容器名称
    container_name: dnmp-mysql
    build:
      context: ./services/mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    # 环境变量
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST}"
      TZ: "$TZ"
    # 端口映射
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    # 磁盘挂载
    volumes:
      - ${MYSQL_CONF_MYSQL_CNF}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_CONF_DIR_DATA}:/var/lib/mysql/:rw
      - ${MYSQL_LOG_DIR}:/var/log/mysql/:rw
    restart: always
    networks:
      - docker-dnmp-default
    

  # 服务名称
  redis:
    # 镜像名称
    image: dnmp-redis:${REDIS_VERSION}
    # 容器名称
    container_name: dnmp-redis
    # 编译文件
    build:
      context: ./services/redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    # 环境变量
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      TZ: "$TZ"
    # 端口映射
    ports:
      - "${REDIS_HOST_PORT}:6379"
    # 磁盘挂载
    volumes:
      - ${REDIS_CONF_REDIS_CONF}:/etc/redis.conf:ro
      - ${REDIS_CONF_DIR_DATA}:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf" , "--requirepass" , "${REDIS_PASSWORD}"]
    restart: always
    networks:
      - docker-dnmp-default


#======================================================================================> [kafka]

  kafka-node1:
    # 容器名称
    container_name: dnmp-kafka-node1
    # 镜像名称
    image: bitnami/kafka:${KAFKA_VERSION}
    user: root
    # 端口映射
    ports:
      - ${KAFKA_PORT_CLIENT_NODE1}:9092
      - ${KAFKA_PORT_CONTROLLER_NODE1}:9093
    # 磁盘挂载
    volumes:
      # 数据目录
      - ${KAFKA_DIR_DATA_NODE1}:/bitnami/kafka:rw
    environment:
      - TZ="$TZ"
      # 指定Kafka节点的ID为1，唯一
      - KAFKA_CFG_NODE_ID=1
      # 启用KRaft模式 , 即Kafka替代Zookeeper
      - KAFKA_ENABLE_KRAFT=yes
      # 设置Kafka节点的角色 既要做 broker 又要做 controller
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # KRaft集群的ID ， 构造一个 UUID 
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      # 指定供外部使用的控制类请求信息
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  
      # 定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      # 监听器的地址为当前节点的IP和相应的端口
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 
      # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # 设置控制器的选举集群成员
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-node1:9093,2@kafka-node2:9093,3@kafka-node3:9093
      # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 禁止自动创建主题
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false 
      # 设置broker最大内存，和初始内存
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
    restart: always
    networks:
      - docker-dnmp-default

  kafka-node2:
    # 容器名称
    container_name: dnmp-kafka-node2
    # 镜像名称
    image: bitnami/kafka:${KAFKA_VERSION}
    user: root
    # 端口映射
    ports:
      - ${KAFKA_PORT_CLIENT_NODE2}:9092
      - ${KAFKA_PORT_CONTROLLER_NODE2}:9093
    # 磁盘挂载
    volumes:
      # 数据目录
      - ${KAFKA_DIR_DATA_NODE2}:/bitnami/kafka:rw
    environment:
      - TZ="$TZ"
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-node1:9093,2@kafka-node2:9093,3@kafka-node3:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false 
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
    restart: always
    networks:
      - docker-dnmp-default

  kafka-node3:
    # 容器名称
    container_name: dnmp-kafka-node3
    # 镜像名称
    image: bitnami/kafka:${KAFKA_VERSION}
    user: root
    # 端口映射
    ports:
      - ${KAFKA_PORT_CLIENT_NODE3}:9092
      - ${KAFKA_PORT_CONTROLLER_NODE3}:9093
    # 磁盘挂载
    volumes:
      # 数据目录
      - ${KAFKA_DIR_DATA_NODE3}:/bitnami/kafka:rw
    environment:
      - TZ="$TZ"
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-node1:9093,2@kafka-node2:9093,3@kafka-node3:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false 
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
    restart: always
    networks:
      - docker-dnmp-default


#======================================================================================> [kafka]



# 网络配置
networks:
  # 定义网络名
  docker-dnmp-default:
    # bridge 驱动
    driver: bridge
    # IP 地址管理相关的配置
    ipam:
      driver: default
      config:
       - subnet: 192.168.10.0/24
